name = "cloudpaste"
main = "worker.js"
compatibility_date = "2024-11-27"

workers_dev = true

[vars]
{{ ... }}

[[kv_namespaces]]
binding = "PASTE_STORE"
id = "placeholder-id"

[[r2_buckets]]
bucket_name = "cloudpaste-files"
binding = "FILE_STORE"